In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("20240121_shopee_sample_data.csv")

In [3]:
df.head()

,price_ori,delivery,item_category_detail,specification,title,w_date,link_ori,item_rating,seller_name,idElastic,price_actual,sitename,idHash,total_rating,id,total_sold,pict_link,favorite,timestamp,desc
0,25.80,"KL City, Kuala Lumpur",Shopee | Women's Bags | Shoulder Bags | Should...,Product Specifications Category Shopee Women's...,1081 PU SLING BAG KULIT leather Casual Beg Tan...,2023-04-27,https://shopee.com.my/1081-PU-SLING-BAG-KULIT-...,4.9,qqfwholesale,19ec9fdedd9fe3e14bc652950fc3c423,12.90,shopee,88f051f0a2dcf0d29191e0175b828938,179,88f051f0a2dcf0d29191e0175b828938,179,https://down-my.img.susercontent.com/file/my-1...,Favorite (128,1682553600000,🎉 WELCOME To QQF WHOLESALE \r\n😍 ALL item read...
1,1.41,NaN,Shopee | Home Appliances | Sewing Machines | S...,Product Specifications Category Shopee Home Ap...,Stat Chinese Traditional Frog Buttons Knot Che...,2023-04-27,https://shopee.com.my/Stat-Chinese-Traditional...,5.0,stationery.my,5322309be3b6d9c01d15fa19f5b7ad9a,0.75,shopee,472d22f58af3bb35cf28c6eed7088dc5,17,472d22f58af3bb35cf28c6eed7088dc5,17,https://down-my.img.susercontent.com/file/4147...,Favorite (19,1682553600000,Chinese Traditional Frog Buttons Knot Cheongsa...
2,8.50,"KL City, Kuala Lumpur",Shopee | Women's Bags | Handbags | Set Handbags,Product Specifications Category Shopee Women's...,N09 READY STOCK MYFOOYIN woman handbag set 2in...,2023-04-26,https://shopee.com.my/N09-READY-STOCK-MYFOOYIN...,4.9,fooyin88,7a36765d1e2ca2b6a5414ddfeedfefc3,8.50,shopee,ec6ce64f4b77efb38b6392818959f181,8.1k,ec6ce64f4b77efb38b6392818959f181,8.1k,https://down-my.img.susercontent.com/file/23da...,Favorite (21.5k,1682467200000,READY STOCK\nMEASUREMENT:\nLONG 26CM X HEIGHT ...
3,8.70,NaN,Shopee | Women Clothes | Maternity Wear | Inne...,Product Specifications Category Shopee Women C...,🔥Shocking Sale🔥Cotton Comfort Nursing Bra Brea...,2023-04-26,https://shopee.com.my/%F0%9F%94%A5Shocking-Sal...,4.9,vivi2002,7fc4ab69722e4f788f217b4c044f83eb,8.70,shopee,ef4e0e17fdc7d0125d8609dcc395bc3d,6.5k,ef4e0e17fdc7d0125d8609dcc395bc3d,6.5k,https://down-my.img.susercontent.com/file/df47...,Favorite (3.4k,1682467200000,PRODUCT DESCRIPTION\nMaterial:95%Cotton+5%Span...
4,3999.00,"KL City, Kuala Lumpur",Shopee | Cameras & Drones | DSLR Cameras | DSLRs,Product Specifications Category Shopee Cameras...,Canon EOS 70D 18-55mm IS STM Original+64gb+ext...,2023-04-26,https://shopee.com.my/Canon-EOS-70D-18-55mm-IS...,5.0,xpro.gadget,55608f901f4c5384f884de18227d4298,2739.00,shopee,568c2029fed7d22973ff96d0404a8ff8,10,568c2029fed7d22973ff96d0404a8ff8,10,https://down-my.img.susercontent.com/file/4d3a...,Favorite (132,1682467200000,Canon 70D\nHighlights\nEF-S 18-55mm f/3.5-5.6 ...

In [4]:
df.shape

(20312, 20)

In [5]:
df.columns

Index(['price_ori', 'delivery', 'item_category_detail', 'specification',
       'title', 'w_date', 'link_ori', 'item_rating', 'seller_name',
       'idElastic', 'price_actual', 'sitename', 'idHash', 'total_rating', 'id',
       'total_sold', 'pict_link', 'favorite', 'timestamp', 'desc'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20312 entries, 0 to 20311
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   price_ori             20112 non-null  float64
 1   delivery              6558 non-null   object
 2   item_category_detail  20312 non-null  object
 3   specification         20301 non-null  object
 4   title                 20312 non-null  object
 5   w_date                20312 non-null  object
 6   link_ori              20312 non-null  object
 7   item_rating           20301 non-null  object
 8   seller_name           20301 non-null  object
 9   idElastic             20312 non-null  object
 10  price_actual          20297 non-null  float64
 11  sitename              20312 non-null  object
 12  idHash                20312 non-null  object
 13  total_rating          20301 non-null  object
 14  id                    20312 non-null  object
 15  total_sold            20301 non-null  object
 16  pict_link             20312 non-null  object
 17  favorite              19242 non-null  object
 18  timestamp             20312 non-null  int64
 19  desc                  20312 non-null  object
dtypes: float64(2), int64(1), object(17)
memory usage: 3.1+ MB

In [7]:
df.isnull().sum()

price_ori                 200
delivery                13754
item_category_detail        0
specification              11
title                       0
w_date                      0
link_ori                    0
item_rating                11
seller_name                11
idElastic                   0
price_actual               15
sitename                    0
idHash                      0
total_rating               11
id                          0
total_sold                 11
pict_link                   0
favorite                 1070
timestamp                   0
desc                        0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
(df == "").sum()

price_ori               0
delivery                0
item_category_detail    0
specification           0
title                   0
w_date                  0
link_ori                0
item_rating             0
seller_name             0
idElastic               0
price_actual            0
sitename                0
idHash                  0
total_rating            0
id                      0
total_sold              0
pict_link               0
favorite                0
timestamp               0
desc                    0
dtype: int64

In [10]:
df.describe()

          price_ori  price_actual     timestamp
count  2.011200e+04  2.029700e+04  2.031200e+04
mean   9.989702e+04  9.893085e+04  1.683323e+12
std    9.971868e+06  9.926322e+06  5.114706e+08
min    0.000000e+00  0.000000e+00  1.682294e+12
25%    2.270000e+00  1.000000e+00  1.682899e+12
50%    1.990000e+01  1.000000e+01  1.683331e+12
75%    8.990000e+01  6.900000e+01  1.683850e+12
max    1.000000e+09  1.000000e+09  1.683936e+12

Initial Data Inspection

1. Dataset size: 20312 rows, 20 columns
2. Number of columns: ['price_ori', 'delivery', 'item_category_detail', 'specification',
       'title', 'w_date', 'link_ori', 'item_rating', 'seller_name',
       'idElastic', 'price_actual', 'sitename', 'idHash', 'total_rating', 'id',
       'total_sold', 'pict_link', 'favorite', 'timestamp', 'desc'],
      dtype='object')
3. Missing values:
      
      price_ori
      200
    
    
      delivery
      13754
    
    
      item_category_detail
      0
    
    
      specification
      11
    
    
      title
      0
    
    
      w_date
      0
    
    
      link_ori
      0
    
    
      item_rating
      11
    
    
      seller_name
      11
    
    
      idElastic
      0
    
    
      price_actual
      15
    
    
      sitename: 0
    
    
      idHash: 0
    
    
      total_rating: 11
    
    
      id: 0
    
    
      total_sold: 11
    
    
      pict_link: 0
    
    
      favorite: 1070
      
      timestamp: 0
      
      desc: 0
      
      dtype: int64

4. Duplicate rows: np.int64(0)
5. Empty strings:
      
      price_ori
      0
    
    
      delivery
      0
    
    
      item_category_detail
      0
    
    
      specification
      0
    
    
      title
      0
    
    
      w_date
      0
    
    
      link_ori
      0
    
    
      item_rating
      0
    
    
      seller_name
      0
    
    
      idElastic
      0
    
    
      price_actual
      0
    
    
      sitename
      0
    
    
      idHash
      0
    
    
      total_rating
      0
    
    
      id
      0
    
    
      total_sold
      0
    
    
      pict_link
      0
    
    
      favorite
      0
    
    
      timestamp
      0
    
    
      desc
      0
    
      dtype: int64

6. Potentially unusual values:
      price_ori	    price_actual	timestamp
count	2.011200e+04	2.029700e+04	2.031200e+04
mean	9.989702e+04	9.893085e+04	1.683323e+12
std	  9.971868e+06	9.926322e+06	5.114706e+08
min	  0.000000e+00	0.000000e+00	1.682294e+12
25%	  2.270000e+00	1.000000e+00	1.682899e+12
50%	  1.990000e+01	1.000000e+01	1.683331e+12
75%	  8.990000e+01	6.900000e+01	1.683850e+12
max	  1.000000e+09	1.000000e+09	1.683936e+12

In [11]:
df.head(10)

,price_ori,delivery,item_category_detail,specification,title,w_date,link_ori,item_rating,seller_name,idElastic,price_actual,sitename,idHash,total_rating,id,total_sold,pict_link,favorite,timestamp,desc
0,25.80,"KL City, Kuala Lumpur",Shopee | Women's Bags | Shoulder Bags | Should...,Product Specifications Category Shopee Women's...,1081 PU SLING BAG KULIT leather Casual Beg Tan...,2023-04-27,https://shopee.com.my/1081-PU-SLING-BAG-KULIT-...,4.9,qqfwholesale,19ec9fdedd9fe3e14bc652950fc3c423,12.90,shopee,88f051f0a2dcf0d29191e0175b828938,179,88f051f0a2dcf0d29191e0175b828938,179,https://down-my.img.susercontent.com/file/my-1...,Favorite (128,1682553600000,🎉 WELCOME To QQF WHOLESALE \r\n😍 ALL item read...
1,1.41,NaN,Shopee | Home Appliances | Sewing Machines | S...,Product Specifications Category Shopee Home Ap...,Stat Chinese Traditional Frog Buttons Knot Che...,2023-04-27,https://shopee.com.my/Stat-Chinese-Traditional...,5.0,stationery.my,5322309be3b6d9c01d15fa19f5b7ad9a,0.75,shopee,472d22f58af3bb35cf28c6eed7088dc5,17,472d22f58af3bb35cf28c6eed7088dc5,17,https://down-my.img.susercontent.com/file/4147...,Favorite (19,1682553600000,Chinese Traditional Frog Buttons Knot Cheongsa...
2,8.50,"KL City, Kuala Lumpur",Shopee | Women's Bags | Handbags | Set Handbags,Product Specifications Category Shopee Women's...,N09 READY STOCK MYFOOYIN woman handbag set 2in...,2023-04-26,https://shopee.com.my/N09-READY-STOCK-MYFOOYIN...,4.9,fooyin88,7a36765d1e2ca2b6a5414ddfeedfefc3,8.50,shopee,ec6ce64f4b77efb38b6392818959f181,8.1k,ec6ce64f4b77efb38b6392818959f181,8.1k,https://down-my.img.susercontent.com/file/23da...,Favorite (21.5k,1682467200000,READY STOCK\nMEASUREMENT:\nLONG 26CM X HEIGHT ...
3,8.70,NaN,Shopee | Women Clothes | Maternity Wear | Inne...,Product Specifications Category Shopee Women C...,🔥Shocking Sale🔥Cotton Comfort Nursing Bra Brea...,2023-04-26,https://shopee.com.my/%F0%9F%94%A5Shocking-Sal...,4.9,vivi2002,7fc4ab69722e4f788f217b4c044f83eb,8.70,shopee,ef4e0e17fdc7d0125d8609dcc395bc3d,6.5k,ef4e0e17fdc7d0125d8609dcc395bc3d,6.5k,https://down-my.img.susercontent.com/file/df47...,Favorite (3.4k,1682467200000,PRODUCT DESCRIPTION\nMaterial:95%Cotton+5%Span...
4,3999.00,"KL City, Kuala Lumpur",Shopee | Cameras & Drones | DSLR Cameras | DSLRs,Product Specifications Category Shopee Cameras...,Canon EOS 70D 18-55mm IS STM Original+64gb+ext...,2023-04-26,https://shopee.com.my/Canon-EOS-70D-18-55mm-IS...,5.0,xpro.gadget,55608f901f4c5384f884de18227d4298,2739.00,shopee,568c2029fed7d22973ff96d0404a8ff8,10,568c2029fed7d22973ff96d0404a8ff8,10,https://down-my.img.susercontent.com/file/4d3a...,Favorite (132,1682467200000,Canon 70D\nHighlights\nEF-S 18-55mm f/3.5-5.6 ...
5,2950.00,NaN,Shopee | Cameras & Drones | Others | Others,Product Specifications Category Shopee Cameras...,"Atomos Ninja Cast Stand-Alone Switcher, Multiv...",2023-04-26,https://shopee.com.my/Atomos-Ninja-Cast-Stand-...,No ratings yet,cameravalley,12707226efd6bd1243f5e32f7a080999,2950.00,shopee,fe3d2c2c407c9ab3b2890b8e24b0873f,0,fe3d2c2c407c9ab3b2890b8e24b0873f,0,https://down-my.img.susercontent.com/file/sg-1...,NaN,1682467200000,"Atomos Ninja Cast Stand-Alone Switcher, Multiv..."
6,19.00,"KL City, Kuala Lumpur",Shopee | Others | Fengshui & Religious Supplies,Product Specifications Category Shopee Others ...,贺加福 （新）九品莲花大悲咒/30.5cmX30.5cm/正背彩色/莲花纸/1包6色/1色2...,2023-04-26,https://shopee.com.my/%E8%B4%BA%E5%8A%A0%E7%A6...,5.0,hokarhock,160d66bd6367d2eb88c6cd8cbfa8de85,19.00,shopee,de28753a7ba4ec8b40b184a62da006fe,17,de28753a7ba4ec8b40b184a62da006fe,17,https://down-my.img.susercontent.com/file/my-1...,Favorite (11,1682467200000,贺加福\r\n（新）九品莲花大悲咒\r\n30.5cmX30.5cm\r\n一色20张， 一...
7,0.49,NaN,Shopee | Mobile & Accessories | Cases & Covers...,Product Specifications Category Shopee Mobile ...,Mobile Phone Smartphone Powerbank Soft Pouch B...,2023-04-24,https://shopee.com.my/Mobile-Phone-Smartphone-...,4.9,orangetechnology,fb4d23b4ac9927fd6f9225cf0e84254b,0.49,shopee,2111886e473c02ed6705488024b50213,493,2111886e473c02ed6705488024b50213,493,https://down-my.img.susercontent.com/file/5874...,Favorite (219,1682294400000,Mobile Phone Smartphone Power bank Soft Pouch ...
8,11.00,"KL City, Kuala Lumpur",Shopee | Men Clothes | Traditional Wear | Bottoms,Product Specifications Category Shopee Men Clo...,Fashion Men's Sheer Thong Low Rise Stretch G-S...,2023-04-24,https://shopee.com.my/Fashion-Men%27s-Sheer-Th...,5.0,mrbunny.my,f95121639c00abd31d1e49c33428d7ff,5.50,shopee,76a30294ff1350e6d26885efa3188d02,17,76a30294ff1350e6d26885efa3188d02,17,https://down-my.img.susercontent.com/file/7654...,Favorite (34,1682294400000,"Details:* Tag Size: L~2XL, Please make sure th..."
9,599.00,"KL City, Kuala Lumpur",Shopee | Mobile & Accessories | Cool Gadgets |...,Product Specifications Category Shopee Mobile ...,Apple Pencil (2nd Generation) | Shopee Malaysia,2023-04-24,https://shopee.com.my/Apple-Pencil-%282nd-Gene...,4.9,switch_os,d4a021872d337c148690b87e8bd0d8ac,449.00,shopee,b366a4324e4b231e6ab53f6bc35962ff,2.9k,b366a4324e4b231e6ab53f6bc35962ff,2.9k,https://down-my.img.susercontent.com/file/my-1...,Favorite (4.3k,1682294400000,Apple Pencil (2nd generation) delivers pixel-p...

In [12]:
df.dtypes

price_ori               float64
delivery                 object
item_category_detail     object
specification            object
title                    object
w_date                   object
link_ori                 object
item_rating              object
seller_name              object
idElastic                object
price_actual            float64
sitename                 object
idHash                   object
total_rating             object
id                       object
total_sold               object
pict_link                object
favorite                 object
timestamp                 int64
desc                     object
dtype: object

In [13]:
df.head(10)

,price_ori,delivery,item_category_detail,specification,title,w_date,link_ori,item_rating,seller_name,idElastic,price_actual,sitename,idHash,total_rating,id,total_sold,pict_link,favorite,timestamp,desc
0,25.80,"KL City, Kuala Lumpur",Shopee | Women's Bags | Shoulder Bags | Should...,Product Specifications Category Shopee Women's...,1081 PU SLING BAG KULIT leather Casual Beg Tan...,2023-04-27,https://shopee.com.my/1081-PU-SLING-BAG-KULIT-...,4.9,qqfwholesale,19ec9fdedd9fe3e14bc652950fc3c423,12.90,shopee,88f051f0a2dcf0d29191e0175b828938,179,88f051f0a2dcf0d29191e0175b828938,179,https://down-my.img.susercontent.com/file/my-1...,Favorite (128,1682553600000,🎉 WELCOME To QQF WHOLESALE \r\n😍 ALL item read...
1,1.41,NaN,Shopee | Home Appliances | Sewing Machines | S...,Product Specifications Category Shopee Home Ap...,Stat Chinese Traditional Frog Buttons Knot Che...,2023-04-27,https://shopee.com.my/Stat-Chinese-Traditional...,5.0,stationery.my,5322309be3b6d9c01d15fa19f5b7ad9a,0.75,shopee,472d22f58af3bb35cf28c6eed7088dc5,17,472d22f58af3bb35cf28c6eed7088dc5,17,https://down-my.img.susercontent.com/file/4147...,Favorite (19,1682553600000,Chinese Traditional Frog Buttons Knot Cheongsa...
2,8.50,"KL City, Kuala Lumpur",Shopee | Women's Bags | Handbags | Set Handbags,Product Specifications Category Shopee Women's...,N09 READY STOCK MYFOOYIN woman handbag set 2in...,2023-04-26,https://shopee.com.my/N09-READY-STOCK-MYFOOYIN...,4.9,fooyin88,7a36765d1e2ca2b6a5414ddfeedfefc3,8.50,shopee,ec6ce64f4b77efb38b6392818959f181,8.1k,ec6ce64f4b77efb38b6392818959f181,8.1k,https://down-my.img.susercontent.com/file/23da...,Favorite (21.5k,1682467200000,READY STOCK\nMEASUREMENT:\nLONG 26CM X HEIGHT ...
3,8.70,NaN,Shopee | Women Clothes | Maternity Wear | Inne...,Product Specifications Category Shopee Women C...,🔥Shocking Sale🔥Cotton Comfort Nursing Bra Brea...,2023-04-26,https://shopee.com.my/%F0%9F%94%A5Shocking-Sal...,4.9,vivi2002,7fc4ab69722e4f788f217b4c044f83eb,8.70,shopee,ef4e0e17fdc7d0125d8609dcc395bc3d,6.5k,ef4e0e17fdc7d0125d8609dcc395bc3d,6.5k,https://down-my.img.susercontent.com/file/df47...,Favorite (3.4k,1682467200000,PRODUCT DESCRIPTION\nMaterial:95%Cotton+5%Span...
4,3999.00,"KL City, Kuala Lumpur",Shopee | Cameras & Drones | DSLR Cameras | DSLRs,Product Specifications Category Shopee Cameras...,Canon EOS 70D 18-55mm IS STM Original+64gb+ext...,2023-04-26,https://shopee.com.my/Canon-EOS-70D-18-55mm-IS...,5.0,xpro.gadget,55608f901f4c5384f884de18227d4298,2739.00,shopee,568c2029fed7d22973ff96d0404a8ff8,10,568c2029fed7d22973ff96d0404a8ff8,10,https://down-my.img.susercontent.com/file/4d3a...,Favorite (132,1682467200000,Canon 70D\nHighlights\nEF-S 18-55mm f/3.5-5.6 ...
5,2950.00,NaN,Shopee | Cameras & Drones | Others | Others,Product Specifications Category Shopee Cameras...,"Atomos Ninja Cast Stand-Alone Switcher, Multiv...",2023-04-26,https://shopee.com.my/Atomos-Ninja-Cast-Stand-...,No ratings yet,cameravalley,12707226efd6bd1243f5e32f7a080999,2950.00,shopee,fe3d2c2c407c9ab3b2890b8e24b0873f,0,fe3d2c2c407c9ab3b2890b8e24b0873f,0,https://down-my.img.susercontent.com/file/sg-1...,NaN,1682467200000,"Atomos Ninja Cast Stand-Alone Switcher, Multiv..."
6,19.00,"KL City, Kuala Lumpur",Shopee | Others | Fengshui & Religious Supplies,Product Specifications Category Shopee Others ...,贺加福 （新）九品莲花大悲咒/30.5cmX30.5cm/正背彩色/莲花纸/1包6色/1色2...,2023-04-26,https://shopee.com.my/%E8%B4%BA%E5%8A%A0%E7%A6...,5.0,hokarhock,160d66bd6367d2eb88c6cd8cbfa8de85,19.00,shopee,de28753a7ba4ec8b40b184a62da006fe,17,de28753a7ba4ec8b40b184a62da006fe,17,https://down-my.img.susercontent.com/file/my-1...,Favorite (11,1682467200000,贺加福\r\n（新）九品莲花大悲咒\r\n30.5cmX30.5cm\r\n一色20张， 一...
7,0.49,NaN,Shopee | Mobile & Accessories | Cases & Covers...,Product Specifications Category Shopee Mobile ...,Mobile Phone Smartphone Powerbank Soft Pouch B...,2023-04-24,https://shopee.com.my/Mobile-Phone-Smartphone-...,4.9,orangetechnology,fb4d23b4ac9927fd6f9225cf0e84254b,0.49,shopee,2111886e473c02ed6705488024b50213,493,2111886e473c02ed6705488024b50213,493,https://down-my.img.susercontent.com/file/5874...,Favorite (219,1682294400000,Mobile Phone Smartphone Power bank Soft Pouch ...
8,11.00,"KL City, Kuala Lumpur",Shopee | Men Clothes | Traditional Wear | Bottoms,Product Specifications Category Shopee Men Clo...,Fashion Men's Sheer Thong Low Rise Stretch G-S...,2023-04-24,https://shopee.com.my/Fashion-Men%27s-Sheer-Th...,5.0,mrbunny.my,f95121639c00abd31d1e49c33428d7ff,5.50,shopee,76a30294ff1350e6d26885efa3188d02,17,76a30294ff1350e6d26885efa3188d02,17,https://down-my.img.susercontent.com/file/7654...,Favorite (34,1682294400000,"Details:* Tag Size: L~2XL, Please make sure th..."
9,599.00,"KL City, Kuala Lumpur",Shopee | Mobile & Accessories | Cool Gadgets |...,Product Specifications Category Shopee Mobile ...,Apple Pencil (2nd Generation) | Shopee Malaysia,2023-04-24,https://shopee.com.my/Apple-Pencil-%282nd-Gene...,4.9,switch_os,d4a021872d337c148690b87e8bd0d8ac,449.00,shopee,b366a4324e4b231e6ab53f6bc35962ff,2.9k,b366a4324e4b231e6ab53f6bc35962ff,2.9k,https://down-my.img.susercontent.com/file/my-1...,Favorite (4.3k,1682294400000,Apple Pencil (2nd generation) delivers pixel-p...

In [14]:
df.dtypes

price_ori               float64
delivery                 object
item_category_detail     object
specification            object
title                    object
w_date                   object
link_ori                 object
item_rating              object
seller_name              object
idElastic                object
price_actual            float64
sitename                 object
idHash                   object
total_rating             object
id                       object
total_sold               object
pict_link                object
favorite                 object
timestamp                 int64
desc                     object
dtype: object

In [15]:
df.nunique()

price_ori                2964
delivery                    1
item_category_detail     1152
specification           19264
title                   16430
w_date                     20
link_ori                16614
item_rating                23
seller_name              9226
idElastic               20312
price_actual             3371
sitename                    1
idHash                  16614
total_rating             1329
id                      16614
total_sold               1329
pict_link               16584
favorite                 1267
timestamp                  20
desc                    16577
dtype: int64

In [17]:
print(df.head(5).to_string())
print("\n--- DATA TYPES ---")
print(df.dtypes.to_string())

   price_ori               delivery                                                          item_category_detail                                                                                                                                                                                                                                      specification                                                                                                                                    title      w_date                                                                                                                                                                                                                                              link_ori item_rating    seller_name                         idElastic  price_actual sitename                            idHash total_rating                                id total_sold                                                                   pict_link         favorite      timestamp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        desc
0      25.80  KL City, Kuala Lumpur                         Shopee | Women's Bags | Shoulder Bags | Shoulder Bags                                                                                                      Product Specifications Category Shopee Women's Bags Shoulder Bags Shoulder Bags Bag Style Boston Material Leather Stock 2906 Ships From Johor  1081 PU SLING BAG KULIT leather Casual Beg Tangan Wanita women Shoulder Wallet Purse Travel READY STOCK QQF WHOLESALE | Shopee Malaysia  2023-04-27                                                                                      https://shopee.com.my/1081-PU-SLING-BAG-KULIT-leather-Casual-Beg-Tangan-Wanita-women-Shoulder-Wallet-Purse-Travel-READY-STOCK-QQF-WHOLESALE-i.794500.16792184278         4.9   qqfwholesale  19ec9fdedd9fe3e14bc652950fc3c423         12.90   shopee  88f051f0a2dcf0d29191e0175b828938          179  88f051f0a2dcf0d29191e0175b828938        179  https://down-my.img.susercontent.com/file/my-11134207-23010-h3ja8ueqrdmv4e    Favorite (128  1682553600000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      🎉 WELCOME To QQF WHOLESALE \r\n😍 ALL item ready stock in Johor \r\n⚠️ HARI HARI posout kecuali public holiday \r\n🤝 SILA jadi Dropship Agent kita\r\n🥰 TANPA syarat & modal\r\n🙌 HARGA borong semua ada listout kat item \r\n👍 HARGA jualan Sila markup sendiri ya\r\n😘 YOU jual kita pos\r\n❌ TAKDA tanda harga\r\n❌ TAKDA resit\r\n❌ TAKDA logo shopee \r\n❤️ APE APE sila chat kat shopee ya\r\n🤝 THKS for your support - Buy 1081 PU SLING BAG KULIT leather Casual Beg Tangan Wanita women Shoulder Wallet Purse Travel READY STOCK QQF WHOLESALE
1       1.41                    NaN  Shopee | Home Appliances | Sewing Machines | Sewing Machines and Accessories                                                                                                       Product Specifications Category Shopee Home Appliances Sewing Machines Sewing Machines and Accessories Stock 31701 Ships From Mainland China                                      Stat Chinese Traditional Frog Buttons Knot Cheongsam Frog Buckle Sewing Fasteners | Shopee Malaysia  2023-04-27                                                                                                                       https://shopee.com.my/Stat-Chinese-Traditional-Frog-Buttons-Knot-Cheongsam-Frog-Buckle-Sewing-Fasteners-i.110639594.11589423326         5.0  stationery.my  5322309be3b6d9c01d15fa19f5b7ad9a          0.75   shopee  472d22f58af3bb35cf28c6eed7088dc5           17  472d22f58af3bb35cf28c6eed7088dc5         17  https://down-my.img.susercontent.com/file/4147ef1ccdabc8c1c6e40fc7042483f2     Favorite (19  1682553600000  Chinese Traditional Frog Buttons Knot Cheongsam Frog Buckle Sewing Fasteners\nFeatures: 100% brand new and high quality\nGourd shape design, simple and generous, smooth lines, fine workmanship, durable.\nPerfect for DIY cheongsams, jackets, cardigans, knitted shawls, belts, sweaters, coats, cushion covers, home decor, gift box decor and crafts. \nPurely handcrafted, with a clear texture and beautiful appearance, it adds a touch of glamour to your outfits. \nSelected high-quality satin material, not easy to break, good toughness, good luster, showing quality. \nSmall and delicate Chinese knot buttons have a chic shape and are suitable for all styles of clothing decoration. \n\nSpecification: Material: Satin\nColor:1/2/3/4/5/6/7/8/9/10/11/12/13/14/15/16/17/18/19/20/21/22/23/24/25/26/27/28/29/30/31/32/33/34/35/36/37/38\nSize: Approx. 7x1.5 cm/2.75x0.59 in\n\nPackage Includes: 1x Gourd Shape Cloth Button\n\nnote: 1.Please allow 1-2cm errors due to manual measurement, make sure that you do not mind before you order. \n2.Due to the difference between different monitors, the picture may not reflect the actual color of the item. - Buy Stat Chinese Traditional Frog Buttons Knot Cheongsam Frog Buckle Sewing Fasteners
2       8.50  KL City, Kuala Lumpur                               Shopee | Women's Bags | Handbags | Set Handbags                                                                                                             Product Specifications Category Shopee Women's Bags Handbags Set Handbags Bag Style Chain Bag Set Yes Stock 2044 Ships From Terengganu                                                              N09 READY STOCK MYFOOYIN woman handbag set 2in1 sling bag | Shopee Malaysia  2023-04-26                                                                                                                                                 https://shopee.com.my/N09-READY-STOCK-MYFOOYIN-woman-handbag-set-2in1-sling-bag-i.24484132.4877043833         4.9       fooyin88  7a36765d1e2ca2b6a5414ddfeedfefc3          8.50   shopee  ec6ce64f4b77efb38b6392818959f181         8.1k  ec6ce64f4b77efb38b6392818959f181       8.1k  https://down-my.img.susercontent.com/file/23dace9eee240c5bc53a21fe33d60534  Favorite (21.5k  1682467200000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              READY STOCK\nMEASUREMENT:\nLONG 26CM X HEIGHT 17CM X WIDTH 8CM - Buy N09 READY STOCK MYFOOYIN woman handbag set 2in1 sling bag
3       8.70                    NaN                           Shopee | Women Clothes | Maternity Wear | Innerwear                                           Product Specifications Category Shopee Women Clothes Maternity Wear Innerwear Pattern Plain Bra Style Others Material Cotton Plus Size Yes Petite No Country of Origin China Stock 386 Ships From Pahang     🔥Shocking Sale🔥Cotton Comfort Nursing Bra Breastfeeding Bra For Pregnancy Women Maternity Underwear B2 衣服 女装 内衣 文胸 | Shopee Malaysia  2023-04-26  https://shopee.com.my/%F0%9F%94%A5Shocking-Sale%F0%9F%94%A5Cotton-Comfort-Nursing-Bra-Breastfeeding-Bra-For-Pregnancy-Women-Maternity-Underwear-B2-%E8%A1%A3%E6%9C%8D-%E5%A5%B3%E8%A3%85-%E5%86%85%E8%A1%A3-%E6%96%87%E8%83%B8-i.11885141.4157729122         4.9       vivi2002  7fc4ab69722e4f788f217b4c044f83eb          8.70   shopee  ef4e0e17fdc7d0125d8609dcc395bc3d         6.5k  ef4e0e17fdc7d0125d8609dcc395bc3d       6.5k  https://down-my.img.susercontent.com/file/df475d312c77bda939138c68fdf6378f   Favorite (3.4k  1682467200000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     PRODUCT DESCRIPTION\nMaterial:95%Cotton+5%Spandex\nCup type    : Full Cup\nMold Cup Type   : Light Mold Cup\nClasp Opening Method  : Front Open Clasp\nUnderwire    : Non-wired\nClasps     : 4 Sets of 4 Hook and Eye Closure\nShoulder Strap Type  : Non-detachable Bra Strap\nColor     : Pink, Skin Color, Light Gray, Deep Gray, Red Bean Paste, Purple, Champagne, Fresh Green\nSize:\nM-34/75\nL-36/80\nXL-38/85\nXXL-40/90\nXXXL-42/95 - Buy 🔥Shocking Sale🔥Cotton Comfort Nursing Bra Breastfeeding Bra For Pregnancy Women Maternity Underwear B2 衣服 女装 内衣 文胸
4    3999.00  KL City, Kuala Lumpur                              Shopee | Cameras & Drones | DSLR Cameras | DSLRs  Product Specifications Category Shopee Cameras & Drones DSLR Cameras DSLRs BrandCanon Warranty Type Supplier Warranty Bundle Set Yes Warranty Duration 3 Years Camera Model 70D Video Capture Resolution FULL HD Stock 36 Ships From Kuala Lumpur                      Canon EOS 70D 18-55mm IS STM Original+64gb+extra battery original (MADE IN JAPAN)3 years Warranty | Shopee Malaysia  2023-04-26                                                                                                     https://shopee.com.my/Canon-EOS-70D-18-55mm-IS-STM-Original-64gb-extra-battery-original-%28MADE-IN-JAPAN%293-years-Warranty-i.46683178.1456495006         5.0    xpro.gadget  55608f901f4c5384f884de18227d4298       2739.00   shopee  568c2029fed7d22973ff96d0404a8ff8           10  568c2029fed7d22973ff96d0404a8ff8         10  https://down-my.img.susercontent.com/file/4d3a4ab73469786af548740181129b09    Favorite (132  1682467200000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Canon 70D\nHighlights\nEF-S 18-55mm f/3.5-5.6 IS STM Lens\n16GB SDHC Memory Card\nShoulder Bag\nSpare Rechargeable Lithium-Ion Battery\n58mm UV Filter\nLCD Screen Protector\nFeatures\nThis Canon EOS 70D DSLR Camera with 18-55mm f/3.5-5.6 IS STM Lens Basic Kit from B&H provides the 20.2MP APS-C format EOS 70D camera with an 18-55mm STM lens, a 16GB SDHC memory card, a spare battery, a wireless remote, a UV & circular polarizer filter kit, and a microfiber cloth. - Buy Canon EOS 70D 18-55mm IS STM Original+64gb+extra battery original (MADE IN JAPAN)3 years Warranty

--- DATA TYPES ---
price_ori               float64
delivery                 object
item_category_detail     object
specification            object
title                    object
w_date                   object
link_ori                 object
item_rating              object
seller_name              object
idElastic                object
price_actual            float64
sitename                 object
idHash                   object
total_rating             object
id                       object
total_sold               object
pict_link                object
favorite                 object
timestamp                 int64
desc                     object

In [18]:
import numpy as np

# 1. Clean 'total_sold' column (convert strings like '8.1k' to numeric floats)
def clean_sold(val):
    if pd.isna(val):
        return 0.0
    val_str = str(val).lower().strip()
    if 'k' in val_str:
        return float(val_str.replace('k', '')) * 1000
    try:
        return float(val_str)
    except:
        return 0.0

df['total_sold_clean'] = df['total_sold'].apply(clean_sold)

# 2. Create a Discount Percentage column (comparing original vs actual price)
# Fill missing original prices with actual prices to avoid NaN errors
df['price_ori_filled'] = df['price_ori'].fillna(df['price_actual'])
df['discount_pct'] = ((df['price_ori_filled'] - df['price_actual']) / df['price_ori_filled']) * 100

# 3. Quick check of our new clean columns
print(df[['title', 'price_actual', 'total_sold_clean', 'discount_pct']].head())

                                               title  price_actual  \
0  1081 PU SLING BAG KULIT leather Casual Beg Tan...         12.90
1  Stat Chinese Traditional Frog Buttons Knot Che...          0.75
2  N09 READY STOCK MYFOOYIN woman handbag set 2in...          8.50
3  🔥Shocking Sale🔥Cotton Comfort Nursing Bra Brea...          8.70
4  Canon EOS 70D 18-55mm IS STM Original+64gb+ext...       2739.00

   total_sold_clean  discount_pct
0             179.0     50.000000
1              17.0     46.808511
2            8100.0      0.000000
3            6500.0      0.000000
4              10.0     31.507877

In [21]:
import sqlite3

In [24]:
conn = sqlite3.connect(':memory:')

In [26]:
df.to_sql('shopee_products', conn, index=False, if_exists='replace')

20312

In [27]:
query = """
SELECT
    item_category_detail,
    COUNT(*) as total_listings,
    ROUND(AVG(price_actual), 2) as avg_price,
    ROUND(SUM(total_sold_clean), 0) as cumulative_units_sold
FROM shopee_products
GROUP BY item_category_detail
ORDER BY cumulative_units_sold DESC
LIMIT 10;
"""

In [28]:
top_categories_sql = pd.read_sql(query, conn)
print(top_categories_sql.to_string())

                                                            item_category_detail  total_listings  avg_price  cumulative_units_sold
0               Shopee | Health & Beauty | Medical Supplies | Health Accessories              68       9.00              1307443.0
1                     Shopee | Home & Living | Home Decor | Rugs, Carpets & Mats              32      30.03               559400.0
2                      Shopee | Baby & Toys | Feeding & Nursing | Bottle Feeding              79      25.14               555298.0
3                     Shopee | Mobile & Accessories | Screen Protectors | Others              43       5.48               553215.0
4                        Shopee | Home & Living | Home Decor | Curtains & Blinds              65      17.78               432462.0
5                          Shopee | Men Clothes | T-shirts & Singlets | T-Shirts             133      21.24               414814.0
6            Shopee | Mobile & Accessories | Powerbanks & Batteries | Powerbanks             119     125.99               407004.0
7  Shopee | Mobile & Accessories | Screen Protectors | Android Screen Protectors              97       3.60               362231.0
8                           Shopee | Home & Living | Bath | Mats, Towels & Robes              59      24.40               350359.0
9                                     Shopee | Men Clothes | Pants | Chinos Pant              35      49.40               342353.0

In [30]:
df.to_csv('shopee_cleaned_analysis_ready.csv', index=False)

In [32]:
print("Dataset has now been exported as 'shopee_cleaned_analysis_ready.csv'")

Dataset has now been exported as 'shopee_cleaned_analysis_ready.csv'